### PR TITLE
Change: Add --python-exit-code to blender calls

### PR DESCRIPTION
**Pull request by grische**
**Purpose of the pull request**  
To let the CI runs not ignore Python exceptions

**Description about the pull request**  
This will show currently silent errors and abort scripts if there has
been a Python exception raised somewhere in Blender.

**Additional comments** [Optional]  
Suggested when reporting https://developer.blender.org/T82494

### CODE REVIEW

**Review by nutti — COMMENTED** [review]
@grische 

Thanks for your proposal.

I have a question.

```bash
${blender_bin} --background --factory-startup -noaudio --python ${SCRIPT_DIR}/gen_modfile/gen_external_modules_modfile.py --python-exit-code 1 -- -m addon_utils -o ${generated_mod_dir}/gen_modules_modfile
```

I'm not sure the effects of  `--` very much.
Does this code work correctly unless the location of  `--python-exit-code 1` moves to the location before `--python ${SCRIPT_DIR}/gen_modfile/gen_external_modules_modfile.py`.

**Comment by nutti** [comment]
@grische 

Thanks for your explanation.
From my understanding and [bug issue on D.B.O](https://developer.blender.org/T82494), I think the location of `--python-exit-code 1` should be before `--python` option.
Is my understanding correct?

* Your code

```bash
${blender_bin} --background --factory-startup -noaudio --python ${SCRIPT_DIR}/gen_modfile/gen_external_modules_modfile.py --python-exit-code 1 -- -m addon_utils -o ${generated_mod_dir}/gen_modules_modfile
```

* Suggestion

```bash
${blender_bin} --background --factory-startup -noaudio --python-exit-code 1 --python ${SCRIPT_DIR}/gen_modfile/gen_external_modules_modfile.py -- -m addon_utils -o ${generated_mod_dir}/gen_modules_modfile
```

**Comment by grische** [comment]
Oh, you are absolutely correct. I fixed this locally two days ago but I forgot to push it 🙈

**Comment by nutti** [comment]
@grische 

Is this PR ready?

**Comment by grische** [comment]
@nutti yes, I marked the "pull request as ready for review".

**Review by nutti — APPROVED** [review]
LGTM

**Comment by nutti** [comment]
@grische 

Thanks a lot! I merged your PR.

**Pull request merged**
