### PR TITLE
Add: Support for Blender v2.91 Beta

### PR DESCRIPTION
**Pull request by grische**
**Purpose of the pull request**  
Testing Blender 2.91 integration early on

**Description about the pull request**  
Adding Blender 2.91 support

**Additional comments** [Optional]  
@nutti there seem to be some Blender issues again. If you had time to check them (or even fix them) it would be great 🙂

### CODE REVIEW

**Comment by nutti** [comment]
@grische 

Thanks for early trial and continuous contribution!
I'll check Blender issue.

**Comment by nutti** [comment]
@grische 

I committed the patch to master branch.
I think this patch will clear errors on CI.
Could you rebase this PR?

**Comment by grische** [comment]
@nutti that looks a lot better, thanks for the quick fix!

Currently, it seems we are missing some data types (new features?)
```
Running test again with fake-bpy-module:
************* Module addon.version_update
intern/cycles/blender/addon/version_update.py:101:11: E1101: Module 'bpy.data' has no 'is_saved' member (no-member)
intern/cycles/blender/addon/version_update.py:106:21: E1101: Module 'bpy.data' has no 'version' member (no-member)
intern/cycles/blender/addon/version_update.py:107:19: E1101: Module 'bpy.data' has no 'libraries' member (no-member)
intern/cycles/blender/addon/version_update.py:117:21: E1101: Module 'bpy.data' has no 'scenes' member (no-member)
intern/cycles/blender/addon/version_update.py:198:21: E1101: Module 'bpy.data' has no 'lights' member (no-member)
intern/cycles/blender/addon/version_update.py:210:21: E1101: Module 'bpy.data' has no 'worlds' member (no-member)
intern/cycles/blender/addon/version_update.py:236:19: E1101: Module 'bpy.data' has no 'materials' member (no-member)
************* Module addon.osl
intern/cycles/blender/addon/osl.py:116:15: E1101: Module 'bpy.data' has no 'as_pointer' member (no-member)
```

**Comment by grische** [comment]
I also noticed this error message, when checking [the build logs](https://github.com/nutti/fake-bpy-module/runs/1368305391):
```
Blender 2.91.0 Beta (hash 02677ec4e0fa built 2020-11-06 00:02:22)
found bundled python: /home/runner/work/fake-bpy-module/fake-bpy-module/blender-bin/blender-v2.91-bin/2.91/python
Traceback (most recent call last):
/home/runner/work/fake-bpy-module/fake-bpy-module/blender/doc/python_api/rst/bmesh.ops.rst
  File "/home/runner/work/fake-bpy-module/fake-bpy-module/blender-bin/blender-v2.91-bin/2.91/scripts/modules/addon_utils.py", line 434, in disable
Exception in module unregister(): '/home/runner/work/fake-bpy-module/fake-bpy-module/blender-bin/blender-v2.91-bin/2.91/scripts/addons/cycles/__init__.py'
    mod.unregister()
  File "/home/runner/work/fake-bpy-module/fake-bpy-module/blender-bin/blender-v2.91-bin/2.91/scripts/addons/cycles/__init__.py", line 153, in unregister
    bpy.app.handlers.version_update.remove(version_update.do_versions)
ValueError: list.remove(x): x not in list
patching file bmesh.ops.rst
patching file freestyle.utils.rst
```

I this expected or something we should investigate?

**Comment by nutti** [comment]
@grische 

I pushed patch to master branch.
I hope this resolve the issue.

P.S. Testing with cycle add-on is great bug finder 👍

**Comment by grische** [comment]
Assuming that [T82493](https://developer.blender.org/T82493) is not a blocker, it looks all good!

**Review by nutti — APPROVED** [review]
LGTM!
Thanks @grische

**Pull request merged**
