### PR TITLE
Update: Support for Blender v4.1

### PR DESCRIPTION
**Pull request by JonathanPlasse**
### Purpose of the pull request

Add support for Blender 4.1

### CODE REVIEW

**Comment by UuuNyaa** [comment]
I think it is better to target the Blender 4.2 LTS API.
Because API changes are already planned for 4.2 LTS.

see: https://developer.blender.org/docs/release_notes/4.2/python_api/

**Comment by JonathanPlasse** [comment]
> I think it is better to target the Blender 4.2 LTS API. Because API changes are already planned for 4.2 LTS.
> 
> see: https://developer.blender.org/docs/release_notes/4.2/python_api/

Blender 4.2 is not out yet.
This change adds 4.1 support, like for all previous versions.
This mean publishing a PyPI package for 4.1.
Latest should have the 4.2 API.

**Comment by UuuNyaa** [comment]
@JonathanPlasse Thank you for the reply and efforts 😀
You are right.

**Review by nutti — APPROVED** [review]

**Comment by nutti** [comment]
Thanks @JonathanPlasse .

@UuuNyaa Thank you also for your comment. We will need to consider your idea for Blender 4.2.

**Comment by JonathanPlasse** [comment]
You are welcome!

**Comment by JonathanPlasse** [comment]
When do you expect `fake-bpy-module-4.1` to be published on PyPI?

**Comment by nutti** [comment]
Before releasing new version, we consider to fix all current issues.

**Comment by JonathanPlasse** [comment]
Will we release for older version too, like 3.3, and 3.6?

**Comment by nutti** [comment]
Sure, we will release old version as well.

**Pull request merged**
