### PR TITLE
Fix: replace bash with env bash and use errexit

### PR DESCRIPTION
**Pull request by grische**
**Purpose of the pull request**  
Making scripts end early if an error occurs, and do not continue silently.

**Description about the pull request**  
Using bash built ins to help in the process.
Also using `/usr/bin/env bash` in the shebang to be compatible with other Linux distro (e.g. [NixOS](https://nixos.org/)).

### CODE REVIEW

**Comment by nutti** [comment]
@grische 

Is this pull request still in progress.
I think all fixed code looks good to me.

**Comment by grische** [comment]
@nutti yes, I want to confirm that the full pipeline with all python versions runs successfully to the end with local CI I am running.
I keep on finding small issues along the way, that's why it is a draft PR.

**Comment by nutti** [comment]
@grische 

Understood.

P.S.
I enabled to trigger the CI when PR is created. Maybe you can use CI infra since now.

**Comment by grische** [comment]
@nutti I added one last commit on top. Can we not squash those commits? It would be easier for me to have separate commits here for later debugging/tracing.

**Comment by nutti** [comment]
@grische 

> Can we not squash those commits? 

Because I do not want to dirty the branch, I usually squash commits.
I think separating issue would be much better style if there are multiple stories.

For this PR, there are 4 different stories. Could you separate PR if it is possible?

**Comment by grische** [comment]
@nutti What do you mean by "clean branch"? Do you mean linear history? That's easy to fix :)

1. Enable branch protection and say "linear history"
image

2. When you merge a PR, you press those buttons
image

This will generate a linear history without merge commits on your target branch.

**Comment by grische** [comment]
@nutti I rebased it on the top of your new master. Do the above steps help you? Or do you still need me to split the PR?

**Comment by nutti** [comment]
@grische 

Sorry, it's my misunderstanding. It can be easily done.

In addition, it's better to create PR per one story because I could trace the patches easily.
Also, I could fix the commit message :)
And you don't need to do force push anymore.

For example in this PR, it is prefer to separate below PRs.

* Replace bash with env bash and use errexit
* Make mkdirs idempotent
* Unintentional failed command during download

**Comment by grische** [comment]
@nutti I added them into a single PR because they all depend on each other.

* Replace bash with env bash and use errexit
Only works if both "Make mkdirs idempotent" and "Unintentional failed command during download" is merged.

In Github unfortunately, it is not possible to make PRs dependent on each other.

**Comment by grische** [comment]
Splitting up PR and converted existing PR to draft PR to avoid merging.

**Comment by grische** [comment]
test message

**Comment by grische** [comment]
I rebased this on top of the current master, but still waiting for #43 to land.

**Pull request merged**
